apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: "nats-cluster"
spec:
  size: {{ .Values.clusterSize }}
  version: "1.3.0"

  pod:
    enableConfigReload: {{ .Values.configReload.enabled }}
    reloaderImage: {{ .Values.configReload.repository }}
    reloaderImageTag: {{ .Values.configReload.tag }}
    reloaderImagePullPolicy: {{ .Values.configReload.pullPolicy }}

    enableMetrics: {{ .Values.metrics.enabled }}
    metricsImage: {{ .Values.metrics.repository }}
    metricsImageTag: {{ .Values.metrics.tag }}
    metricsImagePullPolicy: {{ .Values.metrics.pullPolicy }}

  auth:
    enableServiceAccounts: {{ .Values.auth.enableServiceAccounts }}
    clientsAuthSecret: {{ template "nats.fullname" . }}-clients-auth
    clientsAuthTimeout: 5

  {{- if .Values.tls.enabled }}
  tls:
    # Certificates to secure the NATS client connections:
    serverSecret: {{ .Values.tls.serverSecret }}

    # Certificates to secure the routes.
    routesSecret: {{ .Values.tls.routesSecret }}
  {{- end }}

  debug: {{ .Values.debug }}
  trace: {{ .Values.trace }}
  max_connections: {{ .Values.max_connections }}
  max_payload: {{ .Values.max_payload }}
  write_deadline: {{ .Values.write_deadline }}
